# Email Generator System
# This is a new version of the generator email system
# This program asks for user data and generates an email address automatically


print(f'{"="*20} Email Generator System {"="*20}')

# Data
name = input("Type your name: ").strip()
last_name = input("Type your last name: ").strip()
company = input("Type the name of the company: ").strip()

# Normalize
normalized_name = name.lower().replace(" ",".")
normalized_last_name = last_name.lower().replace(" ", ".")
normalized_company = company.lower().replace(" ", "")
domain = f'.com.mx'

# Email generated
email = f'{normalized_name}.{normalized_last_name}@{normalized_company}{domain}'

# Printing
print(f'''
Name = {name.title()}
Last name = {last_name.title()}
Company name = {company.title()}
Domain = {domain}

Your new email generated by the system is:
{email}
Congratulations!
{'='*60}''')