# This program is for creating a system to generate a unique ID for each person

import random

# Data
name = input('Name: ').strip()
last_name = input('Last name: ').strip()
year = input('Year of birth (YYYY): ').strip()

# Normalize
normalized_name = name[:2].upper()
normalized_last_name = last_name[:2].upper()
normalized_year = year[-2:]

# Random unique factor
value = str(random.randint(0,9999)).zfill(4)

unique_id = f'{normalized_name}{normalized_last_name}{normalized_year}{value}'

# Printing
print(f'''
{"*" * 15} Generator of Unique ID System {"*" * 15}

Name: {name} -> {normalized_name}
Last name: {last_name} -> {normalized_last_name}
Year: {year} -> {normalized_year}
Random value: {value}

Hello, {name.title()}!
Your new identification number (ID) generated by the system is:
{unique_id}
Congratulations!

{"*" * 30}
''')
